### ISSUE TITLE
New user cant install

### ISSUE THREAD

**Issue by mehrd162** [ctsit/form_render_skip_logic#83] opened 2020-10-07 12:00 UTC
Trying to install the module and receiving the following message:

REDCap crashed due to an unexpected PHP fatal error!

Error message: Uncaught Exception: The request to retrieve the name for module 683 from the repo failed: . in C:\inetpub\redcap\redcap_v10.3.3\ExternalModules\classes\ExternalModules.php:4320 Stack trace: #0 C:\inetpub\redcap\redcap_v10.3.3\ExternalModules\manager\ajax\download-module.php(6): ExternalModules\ExternalModules::downloadModule() #1 {main} thrown
File: C:\inetpub\redcap\redcap_v10.3.3\ExternalModules\classes\ExternalModules.php
Line: 4320

Is it possible that the module is designed for a different version of Redcap (10.3.3) or PHP?

Thanks

**Comment by ChemiKyle** [comment] 2021-05-24 17:23
Hi @mehrd162,

Your error appears to have occurred during the fetching of the module. That would be an issue with your system or REDCap core code, not the module; I'm going to close this issue because it's beyond the scope of our module.

Taking a peek at the source code for that process, it looks like you're not getting the name for the module at all from REDCap. Issues could be caused by your firewall settings or your REDCap installation, I'd suggest checking with your institution's IT office; if you're technically inclined you may also want to try spinning up your own instance in Docker: https://github.com/123andy/redcap-docker-compose and seeing if you can download it there while on your institution's network.

**Closed by ChemiKyle** 2021-05-24 17:23 UTC
