### ISSUE TITLE
After 10th Control Field rules, selector Arm-Event dissapears

### ISSUE THREAD

**Issue by cristobalcar** [ctsit/form_render_skip_logic#86] opened 2021-04-14 22:38 UTC
As you can see in this image, the selector for Arm-Event dissapear.
We are currently using v3.3.11 in REDCap 10.8.2

![image](https://user-images.githubusercontent.com/29803674/114789076-8c328e00-9d50-11eb-824f-50331d61d47d.png)

**Comment by ChemiKyle** [comment] 2021-05-21 18:41
There is a possible (even likely) fix for this in the REDCap community


> nathan.orr answered · 5 hours ago
I've managed to solve this issue, but I don't have GitHub account so I'll post the solution here. The issue is with line 56 in the config.js file:
` var suffix = '____' + $radio.attr('name').slice(-1);`
Only the last character of the radio's name is used for the suffix, so the elements with more than 1 digit will not work properly. Changing the line to the code below fixes the problem since it dynamically determines the length of the suffix.
`var suffix =  $radio.attr('name').slice($radio.attr('name').search('____'),$radio.attr('name').length);`

@mbentz-uf could you look into this?

**Comment by ChemiKyle** [comment] 2021-05-24 15:44
Addressed by #87

**Closed by ChemiKyle** 2021-05-24 15:44 UTC
