### ISSUE TITLE
3.3.8 introduces bug on record home page

### ISSUE THREAD

**Issue by mschulze0** [ctsit/form_render_skip_logic#56] opened 2019-09-16 10:27 UTC
Hi,

the changes introduced in 3.3.8 cause FRSL to display the status of instruments incorrectly on the record home page. For example when I try to access a certain instrument that should normally be greyed out (but isn't) the page simply refreshes and only then shows it as being greyed out.

**Comment by pbchase** [comment] 2019-10-11 14:14
@mschulze0, are you using DAGs in this project? We found a bug this morning that might explain what you are seeing. Please take a look at Issue #58 and let us know if that matches your experience. 

We are already working on that issue.

**Comment by mschulze0** [comment] 2019-10-11 14:33
@pbchase yes I'm using DAGs. But this bug is related to viewing an individual record's home page, not the dashboard. Actually I'm not getting any FRSL error when viewing my dashboard, only when I access a record home page I get this error:

`frsl.js?1568627883:28 Uncaught TypeError: Cannot read property '0' of undefined
    at HTMLAnchorElement.<anonymous> (frsl.js?1568627883:28)
    at Function.each (base.js:6)
    at k.fn.init.each (base.js:6)
    at HTMLDocument.<anonymous> (frsl.js?1568627883:21)
(anonymous) @ frsl.js?1568627883:28
each @ base.js:6
each @ base.js:6
(anonymous) @ frsl.js?1568627883:21`

**Comment by pbchase** [comment] 2019-10-11 14:43
@mschulze0, thanks for the detail from the console. That is always helpful. I'll share that with the developer.

**Comment by ChemiKyle** [comment] 2019-10-11 15:54
Hi @mschulze0,

I am able to recreate the error you see from the console but am not seeing instruments clickable when they should be greyed out. In my case, the console error is caused by the module trying to process the "Delete all data on event" buttons in the final row of the table, after all actual instrument links have been processed; this may have _always_ occurred on record home pages. I think the console error may be a red herring in this case, could you please share your project XML and a screenshot of your FRSL config?

**Comment by mschulze0** [comment] 2019-10-11 16:05
@mschulze0 sorry i cannot...both are way too complex haha

**Comment by mschulze0** [comment] 2019-10-11 16:30
@ChemiKyle you only changed a couple of lines from 3.3.7 to 3.3.8...so I guess it should be fairly easy to find out what introduced the incorrect display

**Comment by ChemiKyle** [comment] 2019-10-11 17:33
@mschulze0
I am not able to reproduce your error. That makes it very hard for me to figure out the source of error and fix it. Every bit of detail that you can provide about your environment would make it easier for me to produce your error. If you can reproduce it in a simplified copy of your project and its configuration, that would be immensely helpful. I have found the project XML exports that other people have shared with me to be immensely helpful in reproducing errors.

**Comment by mschulze0** [comment] 2019-10-11 17:45
@ChemiKyle 

`        // Do not load FRSL on the add/edit record splash page
        if ( strpos(PAGE, 'DataEntry/record_home.php') !== false && (!$_GET['arm'] || !$_GET['id']) ) {
            return;
        }`

This addition is the problem as the arm variable doesn't (always?) get set when you return to the record home page after editing a form. For example after editing a record I return to this page: record_home.php?pid=22&id=45&msg=edit
So FRSL simply doesn't get loaded. Changing || to && should probably fix it.

**Comment by ChemiKyle** [comment] 2019-10-11 19:26
@mschulze0 

I had considered that, but if that were the case you would not have seen the console error that you did since the module would have not loaded. However, now that you have mentioned this occurred after editing a form I am now able to recreate it - the `arm.` is indeed not sent if I **Save & Exit Form**, thank you for including that information.

**Comment by mschulze0** [comment] 2019-10-11 20:01
@ChemiKyle actually the error is probably not from the same page load, but remained in the log from a previous page load where FRSL did get loaded..haha sorry about that.

**Comment by pbchase** [comment] 2019-10-11 20:47
addressed by PR #61 and PR #60

**Closed by pbchase** 2019-10-11 20:47 UTC
Labels: bug
