### ISSUE TITLE
REDCap 9.0.3 broke FRSL

### ISSUE THREAD

**Issue by mschulze0** [ctsit/form_render_skip_logic#45] opened 2019-05-27 08:21 UTC
Hi,

9.0.3 broke the module when clicking Add / Edit records showing the following error:

The 'hook_every_page_top' hook did not complete for the 'form_render_skip_logic' module because of the following error:

Error Message: Uncaught Error: Call to a member function getUniqueEventNames() on null in /var/www/html/redcap/redcap_v9.0.3/Classes/LogicTester.php:336
Stack trace:
#0 /var/www/html/redcap/modules/form_render_skip_logic_v3.3.5/ExternalModule.php(305): LogicTester::logicPrependEventName(' if(chkNull([sc...', 'screening_phase...')
#1 /var/www/html/redcap/modules/form_render_skip_logic_v3.3.5/ExternalModule.php(374): FormRenderSkipLogic\ExternalModule\ExternalModule->getFormsAccessMatrix(157, NULL)
#2 /var/www/html/redcap/modules/form_render_skip_logic_v3.3.5/ExternalModule.php(51): FormRenderSkipLogic\ExternalModule\ExternalModule->loadFRSL('record_home', NULL)
#3 [internal function]: FormRenderSkipLogic\ExternalModule\ExternalModule->redcap_every_page_top('22')
#4 /var/www/html/redcap/redcap_v9.0.3/ExternalModules/classes/ExternalModules.php(1415): call_user_func_array(Array, Array)
#5 /var/www/html/redcap/redcap_v9.0.3/ExternalModules/classes/ExternalModules.php(1508): ExternalModules\ExternalModules::startHook('form_rende
File: /var/www/html/redcap/redcap_v9.0.3/Classes/LogicTester.php
Line: 336

**Comment by mijeflo** [comment] 2019-06-04 09:09
This issue also occurred in RC 8.10.18:

> Fatal error: Uncaught Error: Call to a member function getUniqueEventNames() on null in /var/www/survey/redcap_v8.10.18/Classes/LogicTester.php:336
Stack trace:
#0 /var/www/survey/modules/form_render_skip_logic_v3.3.5/ExternalModule.php(305): LogicTester::logicPrependEventName(' chkNull([visit...','visite_3_cru_ta...')
#1 /var/www/survey/modules/form_render_skip_logic_v3.3.5/ExternalModule.php(374): FormRenderSkipLogic\ExternalModule\ExternalModule->getFormsAccessMatrix(60, NULL)
#2 /var/www/survey/modules/form_render_skip_logic_v3.3.5/ExternalModule.php(51):
FormRenderSkipLogic\ExternalModule\ExternalModule->loadFRSL('record_status_d...', NULL)
#3 [internal function]: FormRenderSkipLogic\ExternalModule\ExternalModule->redcap_every_page_top('24')
#4 /var/www/survey/redcap_v8.10.18/ExternalModules/classes/ExternalModules.php(1415): call_user_func_array(Array, Array)
#5 /var/www/survey/redcap_v8.10.18/ExternalModules/classes/ExternalModules.php(1508): ExternalModules\ExternalModules::startHook('form_render_ski...', 'v3.3.5
in /var/www/survey/redcap_v8.10.18/Classes/LogicTester.php on line 336

**Comment by pbchase** [comment] 2019-06-04 13:31
We're looking into this, but I think we might need more detail to replicate the issues. I say this because we are having good results with an extremely complex FRSL config in RC 8.11.2. Can you share some config details? Maybe some screenshots? The failure in `Classes/LogicTester.php` suggests you are using an advanced control field. That contents of that field could be very valuable.

**Comment by mschulze0** [comment] 2019-06-04 14:33
@pbchase 8.11.2 is an old version while 9.0.3 and 8.10.18 (that's an LTS version) were both just released last week. Maybe try to replicate the error using these new versions?

**Comment by pbchase** [comment] 2019-06-04 15:21
@mschulze0, I didn't realize 8.10.18 was younger than 8.11.2. Thanks for that info.

**Comment by pbchase** [comment] 2019-06-04 16:13
Only failing with advanced control fields as I suspected. We can now reproduce it.

**Comment by pbchase** [comment] 2019-06-04 21:46
Addressed by PR #46

**Comment by pbchase** [comment] 2019-06-04 21:51
Released in release 3.3.7

**Comment by pbchase** [comment] 2019-06-04 21:55
FYI, bug do not exist in REDCap 9.0.2.

**Comment by mschulze0** [comment] 2019-06-05 11:09
@pbchase great, thanks a lot! Looking forward to it being available in the repository.

**Comment by pbchase** [comment] 2019-06-06 18:44
Submitted to REDCap Repo just now

**Closed by pbchase** 2019-06-06 18:44 UTC
